DELETE FROM `employee`;
INSERT INTO `employee` (`id`, `code`) VALUES (1,  'elena');
INSERT INTO `employee` (`id`, `code`) VALUES (2,  'natalie');

DELETE FROM `service`;
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (1, 'haircut_man', 30);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (2, 'haircut_women', 30);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (3, 'haircut_child', 30);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (4, 'color_simple', 30);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (5, 'color_complex', 60);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (6, 'color_highlight', 120);
INSERT INTO `service` (`id`, `code`, `duration`) VALUES (7, 'perm', 60);

DELETE FROM `employee_service`;
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 1);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 2);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 3);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 4);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 5);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 6);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (1, 7);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 1);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 2);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 3);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 4);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 5);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 6);
INSERT INTO `employee_service` (`employee_ref`, `service_ref`) VALUES (2, 7);

DELETE FROM `employee_time_work`;
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201026');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201027');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201028');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201029');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201030');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201031');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201101');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201102');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201103');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201104');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (1, '20201105');
INSERT INTO `employee_time_work` (`employee_ref`, `date`) VALUES (2, '20201106');
